kind: ConfigMap
apiVersion: v1
metadata:
  name: order-service
  labels:
    app: order-service
  namespace: default
data:
  application.yml: |-
    endpoints.trace.sensitive: false
    backend:
      ribbon:
        eureka.enabled: false
        client.enabled: true
        ServerListRefreshInterval: 15000