apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: order-service
        image: orderfinalo-s3:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8093
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: native
        - name: VERSION
          value: 'K8S_TIMESTAMP'
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
                name: mysqlbatch-user-pass
                key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysqlbatch-user-pass
                key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
                    name: mysqlbatch-db-url
                    key: url
        - name: STOCK_THRESH
          valueFrom:
            configMapKeyRef:
                    name: stock-threshold1
                    key: thresh1
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service

spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 8093
    targetPort: 8093
    nodePort: 31496
  selector:
    app: order-service
