apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: catalog-service
        image: catalog-final5:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: native
        - name: VERSION
          value: 'K8S_TIMESTAMP'
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
                name: mysqlbatch-user-pass
                key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysqlbatch-user-pass
                key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
                    name: mysqlbatch-db-url
                    key: url
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service

spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 8090
    targetPort: 8090
    nodePort: 31092
  selector:
    app: catalog-service
